### ISSUE TITLE
Misunderstanding on GRID_INDEX_SHIFT

### ISSUE THREAD

**Issue by mhasadi78** [VV0nd3rer/studying-algorithms#1]
It doesn't make sense to me why you're using the whole GRID_INDEX_SHIFT thing, could you please give me an explanation?

Thanks.

**Comment by VV0nd3rer** [comment]
Because Percolation system API specifies that the row and column indices are between 1 and n. Java implementation works with array between 0 and n-1. See more: https://coursera.cs.princeton.edu/algs4/assignments/percolation/faq.php
